#icons_format = "{icon}"
[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:30) $play $next $volume|}"
player = "ncspot"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"

[[block]]
block = "custom"
command = "/usr/bin/xkb-switch -W"
interval = "once"
persistent = true

[[block]]
block = "custom"
cycle = ["echo OFF", "echo ON"]
interval = "once"
[[block.click]]
button = "left"
cmd = "~/.scripts/lights/strip_toggle"

[[block]]
block = "custom"
command = ''' ~/.scripts/statusbar/kraken-ticker '''
interval = 120

[[block]]
block = "custom"
command = ''' ~/.scripts/statusbar/poeninja '''
interval = 120

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "nvidia_gpu"
format = " $icon $utilization $temperature $clocks "


[[block]]
block = "temperature"
scale = "celsius"
format = " $icon $min min, $max max, $average avg "
interval = 5
chip = "coretemp-isa-*"

[[block]]
block = "sound"
device_kind = "source"
driver = "pulseaudio"

[[block]]
block = "sound"
driver = "pulseaudio"
format = "$icon $output_description $volume"

[[block]]
block = "time"
interval = 5
