icons= "awesome"
[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "custom"
command = ''' ~/.scripts/statusbar/poeninja '''
interval = 120

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "nvidia_gpu"
label = "RTX3070"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
chip = "*-isa-*"
format = "{max} max, {average} avg"
inputs = ["CPUTIN", "SYSIN"]

[[block]]
block = "sound"
device_kind = "source"
driver = "pulseaudio"
[[block]]
block = "sound"
driver = "pulseaudio"
format = "{output_description} {volume}"

[[block]]
block = "time"
interval = 5
