icons= "awesome"
[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "battery"
interval = 10
format = "{percentage:6#100} {percentage} {time}"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
chip = "*-isa-*"
format = "{max} max, {average} avg"
inputs = ["CPUTIN", "SYSIN"]

[[block]]
block = "sound"
device_kind = "source"
driver = "pulseaudio"

[[block]]
block = "sound"
driver = "pulseaudio"
format = "{volume}"

[[block]]
block = "time"
interval = 5
