[theme]
theme = "slick"

[icons]
icons= "material-nf"

[[block]]
block = "custom"
command = "/usr/bin/xkb-switch -W"
interval = "once"
persistent = true

[[block]]
block = "battery"
format = "$icon $percentage $time"
device = "BAT0"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization $frequency"
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "temperature"
scale = "celsius"
format = " $icon $min min, $max max, $average avg "
interval = 5
chip = "coretemp-isa-*"

[[block]]
block = "sound"
device_kind = "source"
driver = "pulseaudio"

[[block]]
block = "sound"
driver = "pulseaudio"
format = "$icon {$volume|}"

[[block]]
block = "time"
interval = 5
